####################
# AI hunter general
####################
day_and_clear_weather_on_hunter_toggle: True

####################
# AI hunter armed
####################
hunter_armed_food_regen_level: 20
hunter_armed_invulnerable: False
hunter_armed_saturation: 10
hunter_armed_saturation_regen_rate: 1
hunter_armed_max_health: 500
hunter_armed_health: 500
hunter_armed_food_level: 20
# To remove item set the value to 'AIR'
hunter_helmet: 'CARVED_PUMPKIN'
hunter_chestplate: 'IRON_CHESTPLATE'
hunter_leggings: 'IRON_LEGGINGS'
hunter_boots: 'GOLDEN_BOOTS'
hunter_main_hand_item: 'IRON_SWORD'
hunter_off_hand_item: 'SHIELD'
hunter_blocks: 'COBBLESTONE'
hunter_axe: 'STONE_AXE'
hunter_main_pickaxe: 'DIAMOND_PICKAXE'
hunter_secondary_pickaxe: 'IRON_PICKAXE'
hunter_shovel: 'GOLDEN_SHOVEL'
hunter_bucket: 'WATER_BUCKET'
hunter_food: 'COOKED_BEEF'
#
hunter_armed_pvp: True
hunter_move_delay_seconds: 10

####################
# AI Hunter disarmed
####################
hunter_disarmed_invulnerable: False
hunter_disarmed_saturation: 0
hunter_disarmed_saturation_regen_rate: 1
hunter_disarmed_max_health: 20
hunter_disarmed_health: 20
hunter_disarmed_food_level: 20
hunter_disarmed_pvp: True
