# AI hunter armed
hunter_armed_food_regen_level: 20
hunter_armed_move_delay_seconds: 10
hunter_armed_invulnerable: False
hunter_armed_saturation: 10
hunter_armed_saturation_regen_rate: 1
hunter_armed_max_health: 500
hunter_armed_health: 500
hunter_armed_food_level: 20
hunter_armed_helmet: 'CARVED_PUMPKIN'
hunter_armed_chestplate: 'IRON_CHESTPLATE'
hunter_armed_leggings: 'IRON_LEGGINGS'
hunter_armed_boots: 'GOLDEN_BOOTS'
hunter_armed_pvp: True

# AI Hunter disarmed
hunter_disarmed_invulnerable: False
hunter_disarmed_saturation: 0
hunter_disarmed_saturation_regen_rate: 1
hunter_disarmed_max_health: 20
hunter_disarmed_health: 20
hunter_disarmed_food_level: 20
hunter_disarmed_helmet: 'AIR'
hunter_disarmed_chestplate: 'AIR'
hunter_disarmed_leggings: 'AIR'
hunter_disarmed_boots: 'AIR'
hunter_disarmed_pvp: True
